package com.entity;

import java.util.List;

public class Jurisdiction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.jId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    private Integer jid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.jName
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    private String jname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.roleUrl
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    private String roleurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.flag
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.jId
     *
     * @return the value of jurisdiction.jId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public Integer getJid() {
        return jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.jId
     *
     * @param jid the value for jurisdiction.jId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public void setJid(Integer jid) {
        this.jid = jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.jName
     *
     * @return the value of jurisdiction.jName
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public String getJname() {
        return jname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.jName
     *
     * @param jname the value for jurisdiction.jName
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public void setJname(String jname) {
        this.jname = jname == null ? null : jname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.roleUrl
     *
     * @return the value of jurisdiction.roleUrl
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public String getRoleurl() {
        return roleurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.roleUrl
     *
     * @param roleurl the value for jurisdiction.roleUrl
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public void setRoleurl(String roleurl) {
        this.roleurl = roleurl == null ? null : roleurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.flag
     *
     * @return the value of jurisdiction.flag
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.flag
     *
     * @param flag the value for jurisdiction.flag
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    
    
    //存子菜单
    private List<Jurisdiction> son;

	public List<Jurisdiction> getSon() {
		return son;
	}

	public void setSon(List<Jurisdiction> son) {
		this.son = son;
	}
}