package com.entity;

public class Rj {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rj.rjId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    private Integer rjid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rj.rId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rj.jId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    private Integer jid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rj.rjId
     *
     * @return the value of rj.rjId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public Integer getRjid() {
        return rjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rj.rjId
     *
     * @param rjid the value for rj.rjId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public void setRjid(Integer rjid) {
        this.rjid = rjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rj.rId
     *
     * @return the value of rj.rId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rj.rId
     *
     * @param rid the value for rj.rId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rj.jId
     *
     * @return the value of rj.jId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public Integer getJid() {
        return jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rj.jId
     *
     * @param jid the value for rj.jId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public void setJid(Integer jid) {
        this.jid = jid;
    }
    
    //一个角色对应多个菜单
    private Jurisdiction jurisdiction;

	public Jurisdiction getJurisdiction() {
		return jurisdiction;
	}

	public void setJurisdiction(Jurisdiction jurisdiction) {
		this.jurisdiction = jurisdiction;
	}
}