package com.entity;

public class Rt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt.rtId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    private Integer rtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt.rId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt.tId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt.rtId
     *
     * @return the value of rt.rtId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public Integer getRtid() {
        return rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt.rtId
     *
     * @param rtid the value for rt.rtId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public void setRtid(Integer rtid) {
        this.rtid = rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt.rId
     *
     * @return the value of rt.rId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt.rId
     *
     * @param rid the value for rt.rId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt.tId
     *
     * @return the value of rt.tId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt.tId
     *
     * @param tid the value for rt.tId
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}