package com.dao;

import java.util.List;

import com.entity.Jurisdiction;

public interface JurisdictionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    int deleteByPrimaryKey(Integer jid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    int insert(Jurisdiction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    int insertSelective(Jurisdiction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    Jurisdiction selectByPrimaryKey(Integer jid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    int updateByPrimaryKeySelective(Jurisdiction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    int updateByPrimaryKey(Jurisdiction record);
    
    
    //查询子菜单
    List<Jurisdiction> getS(Integer jId);
}