package com.dao;

import java.util.List;

import com.entity.Rj;

public interface RjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rj
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    int deleteByPrimaryKey(Integer rjid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rj
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    int insert(Rj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rj
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    int insertSelective(Rj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rj
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    Rj selectByPrimaryKey(Integer rjid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rj
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    int updateByPrimaryKeySelective(Rj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rj
     *
     * @mbggenerated Tue Mar 27 18:10:46 CST 2018
     */
    int updateByPrimaryKey(Rj record);
    
    
    //查询每个角色对应的菜单
    List<Rj> getRjs(Integer rId);
}